### ISSUE TITLE
Avatax API has been updated to 19.4 but SDK is still on 19.3 which breaks the AuditTransactionModel and the call to AuditTransaction

### ISSUE THREAD

**Issue by PaterickB** [avadev/AvaTax-REST-V2-DotNet-SDK#102]
An exception is thrown using the AuditTransaction() call.

"Unexpected character encountered while parsing value: {. Path
'original.request', line 1, position 1950."

Updating the API without updating the SDK broke our process to commit tax information and we are scrambling to come up with a solution.  I would also like to say that updating the API at the end of the month when your customers are closing the month is not good!  Doubly so if both the SDK and API are not kept in sync.

Any ETA on when the 19.4 SDK will be released?  Is there a simple workaround to this issue?

**Comment by contygm** [comment]
This issue has been fixed with the 19.4.1 patch. If you update to the 19.4.1 version, the problem should be resolved.

If the problem persists, please reopen this issue.
