### ISSUE TITLE
Question: How to set TaxIncluded?

### ISSUE THREAD

**Issue by babakarj** [avadev/AvaTax-REST-V2-DotNet-SDK#110]
Base on this blog entry: https://developer.avalara.com/blog/2017/11/08/calculating-taxIncluded/
How can we set `taxIncluded` in this library?

**Comment by babakarj** [comment]
Please, see this pull request, too.
https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/pull/111

**Comment by jwenger100** [comment]
This functionality is implemented in the following method:

 `public TransactionBuilder WithTaxIncludeLineItem(decimal amount, decimal quantity = 1, string taxCode = null, string description = null, string itemCode = null, string lineNumber = null, string entityUseCode = null)`
