### ISSUE TITLE
Add ability to log API calls and results

### ISSUE THREAD

**Issue by ted-spence-avalara** [avadev/AvaTax-REST-V2-DotNet-SDK#12]
As a customer using the REST SDK,
I would like a way to write logs of my API calls to a file,
So that I can debug code that works against my account and understand what happened.

**Comment by Minx-SigEp** [comment]
@ted-spence-avalara take a look at #21. Thanks

**Comment by ted-spence-avalara** [comment]
Reviewing now, thanks for the PR!

**Comment by ted-spence-avalara** [comment]
This is now merged into the mainstream SDK with this pull request: https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/pull/41

You can capture the results by hooking the API call event or by calling LogToFile.

```
// You can capture logs to disk like this:
client.LogToFile("c:\\logs\\avataxapi.log");
// Or you can hook the client to capture information about every API call like this:
Client.CallCompleted += MyEventHandler;
```
