### ISSUE TITLE
How to point this SDK to a different endpoint?

### ISSUE THREAD

**Issue by mattheww-freshview** [avadev/AvaTax-REST-V2-DotNet-SDK#138]
As per https://help.avalara.com/Frequently_Asked_Questions/AvaTax_FAQ/What_do_I_need_to_do_about_the_AvaTax_SSL_certificate_change_on_July_13%2C_2020%3F, there is an upcoming cert change. We want to test by pointing our codebase at the test servers to be sure they will work.

How do I do this?

**Comment by StrangeWill** [comment]
We got the same e-mail and we were looking to test it (even though .NET should just use your OS store and be fine... you can do some silly things to break that).

Sadly though, the URL is configured via an enum which only has two options: https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/blob/70f846f025dbdc8a0375cc40db604622746d8d8b/src/AvaTaxClient.cs#L64

`_envUri` is private, so we change that that on either unless you want to do some awful reflection after initializing the class.

For the most part: your developers would have to do something _especially_ awful to break this. It's just a certificate renewal, which can bite people like those that use Java with a custom cert store that they manually inject certificates into.

**Comment by Anras573** [comment]
Actually this library does support it.

https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/blob/master/src/AvaTaxClient.cs#L78-L83

You can supply your own endpoint uri in the constructor.

```csharp
var Client = new AvaTaxClient(
        appName: "MyTestApp",
        appVersion: "1.0",
        machineName: Environment.MachineName,
        customEnvironment: new Uri("https://sandbox-rest-test.avatax.com"))
    .WithSecurity("MyUsername", "MyPassword");
```

**Comment by macdonaldster** [comment]
If you prefer not to recompile the source, you can use Fiddler to do this (https://www.telerik.com/download/fiddler).

1. Get Fiddler working so that your traffic is proxying through it:
```
<system.net>
    <defaultProxy>
      <proxy autoDetect="false" bypassonlocal="false" proxyaddress="http://127.0.0.1:8888" usesystemdefault="false" />
    </defaultProxy>
  </system.net>
```
2. Open Rules > Custom Rules - opens the custom rules editor
3. Find "static function OnBeforeRequest(oSession: Session) {"
4. Add these two methods:
```
		if( oSession.HostnameIs("sandbox-rest.avatax.com") )
		{
			oSession.hostname = "sandbox-rest-test.avatax.com";
		}

		if( oSession.HostnameIs("rest.avatax.com") )
		{
			oSession.hostname = "rest-test.avatax.com";
		}

```
5. Save and close the Custom Rules editor 

Your requests should now go to the "-test" server.

**Comment by Anras573** [comment]
@macdonaldster you don't have to recompile the source.
The source already contains a constructor that'll allow you to pass in a custom endpoint 😃

**Comment by macdonaldster** [comment]
@Anras573 that's an edit to the Fiddler Custom Rules script so that it will "just work" without rebuilding your application to call that custom endpoint, etc. The proxy changes the host when the request is made and passes through it.

**Comment by john-vellozzi-avalara** [comment]
Looks like this has been answered.
