### ISSUE TITLE
Invalid response type BuildTaxContentFile(ForLocation)(Async)

### ISSUE THREAD

**Issue by omeaart** [avadev/AvaTax-REST-V2-DotNet-SDK#145]
The BuildTaxContentFileForLocationAsync method tries to deserialize the response to a FileResult, but the actual response is just a string. And depending on the given responseType it returns Json/Xml/Csv, but never in a FileResult format. So the current implementation throws always a deserialization error.

**Comment by jwenger100** [comment]
Code is committed, targeted for 6/30/22 22.6.0 release of the SDK.
