### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by HakanL** [avadev/AvaTax-REST-V2-DotNet-SDK#16]
Would be great if you can support .NET Core 1.1. I see there is some .NET Standard support, but it doesn't work in .NET Core 1.1.

**Comment by ted-spence-avalara** [comment]
Hi Hakan!

Our NuGet package includes support for NetStandard and should work with NetCore.  May I ask what version of NetCore you are using?  I'm currently having our QA team add test suites for multiple different dot net versions; I'd like to make sure I get your version as well.

**Comment by HakanL** [comment]
I tried to add it to .NET Core 1.1 (VS2017) and it said the NuGet package didn't include a build for it. I downloaded the source and just created a new .NET Standard project and added the files. I had to define PORTABLE in the build config on the project. After that I was able to generate a NuGet package and use it in my .NET Core 1.1 project in VS2017.

**Comment by ted-spence-avalara** [comment]
Thanks for mentioning this.  Something appears to have gone wrong in the NuGet packager; this project was originally designed to be usable in both regular DotNet and DotNetCore.  I'm preparing a patch that includes better support for at least Net20, Net45, and NetStandard11.

**Comment by ted-spence-avalara** [comment]
Thanks to @phillip-tsui-avalara we have a working version that is on NetStandard16, and we've been successfully able to import it into a DotNetCore project.  This will be released with the June 17.6 patch.
