### ISSUE TITLE
Thread safety issue in AvaTaxOfflineHelper

### ISSUE THREAD

**Issue by mattheww-freshview** [avadev/AvaTax-REST-V2-DotNet-SDK#184]
Dictionary is not thread-safe in C# - so if two methods call `GetLocalTaxRateByZip` at the same time then the dictionary may be "corrupted".

Consider using a `ConcurrentDictionary` instead.

https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/blob/b80b902253122a00e7e14a2c146c2abcc8760456/tests/net461/AvaTaxOfflineHelper.cs#L30

**Comment by jwenger100** [comment]
Code is committed, targeted for 6/30/22 22.6.0 release.
