### ISSUE TITLE
customerUsageType is DEPRECATED - how to set entityUseCode instead?

### ISSUE THREAD

**Issue by mauriciojsola** [avadev/AvaTax-REST-V2-DotNet-SDK#70]
Hi, the "customerUsageType" says: "DEPRECATED - Please use `entityUseCode` instead.".
How can that "entityUseCode" be set by using this SDK?
Am I missing something?
Thanks in advance!

**Comment by Minx-SigEp** [comment]
I too have wondered this. we are still using the customerUsageType at this point.

**Comment by zbenjamin123** [comment]
A year later and I am wondering the same thing.  Did anyone find an answer?
