### ISSUE TITLE
AvaTaxClient.UploadCertificateImage() not fully implemented?

### ISSUE THREAD

**Issue by JarrenLong** [avadev/AvaTax-REST-V2-DotNet-SDK#92]
Started looking at the source while working on implementing this API in our in-house application, and trying to troubleshoot why this function was consistently failing almost immediately. It does not look like the FileResult argument is used within the function at all, which could explain why I have not been able to successfully upload a certificate to AvaTax/CertCapture.

**Comment by JarrenLong** [comment]
Refer to https://community.avalara.com/avalara/topics/c-api-uploadcertificateimage for more info.

**Comment by WayneMyerAvalara** [comment]
The UploadCertificateImage method is incomplete. PR #93 is the fix, awaiting pass of the 19.4 SDK.

**Comment by JarrenLong** [comment]
Thanks for knocking this out Wayne, I'll consume the 19.4.0 nuget package as soon as I see it available and give it a shot.

**Comment by WayneMyerAvalara** [comment]
Because of the additional change, the new code will most likely be in 19.4.1, following shortly after the CI greenlights 19.4.0.

**Comment by JarrenLong** [comment]
Hi Wayne, I've pulled in the v19.4.1 nuget package, but I am still seeing that this function is not behaving correctly. Did this fix get integrated?

**Comment by WayneMyerAvalara** [comment]
Hi Jarren, we had another issue to resolve and the branch for UploadCertificateImage got pushed aside. The PR https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/pull/107 has the fix. We will merge that branch at some point.

**Comment by JarrenLong** [comment]
Follow up: Looks like this got merged in for the v19.5.0 release, tested and working. Thanks!
